GET http://localhost:8081/hello
#Accept: application/json

> {%
 client.test("test-hello", function (){
     client.log("测试/hello接口");
     client.log(response.body);
     client.log(JSON.stringify(response.body));
     client.assert(response.status === 200,"返回码不是200");
 });
 %}


###
POST http://localhost:8080/hello/post
Content-Type: application/x-www-form-urlencoded

name=Test

###

POST http://localhost:8081/category/save
Accept: application/json
token: 40250069529792512

###
GET http://localhost:8081/redis/set/123/test
Accept: application/json


###
GET http://localhost:8081/redis/get/40250069529792512
Accept: application/json

###
POST http://127.0.0.1:8081/user/logout/40250069529792512
Accept: application/json
token: 40250069529792512